kryoInstancePoolCapacity: 100
kryoOutputPoolCapacity: 100
kryoInputPoolCapacity: 100
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.132:3306/warhammer?characterEncoding=utf-8&useSSL=false
    username: root
    password: woshinige52.
  data:
    redis:
      host: 192.168.3.243
      port: 6379
      database: 0